name: Factory-Safety

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To Server
        uses: appleboy/ssh-action@master

        with:
          host: 72.62.186.142
          username: root
          password: lq)v/Tr0Ur4ltHTj
          script: |
            cd /root/Factory-Safety
            git pull origin master

            # restart queue worker
            php artisan queue:restart
            pkill -f "queue:work" || true
            nohup php artisan queue:work > queue.log 2>&1 &

            # restart Reverb
            pkill -f "reverb" || true
            nohup php artisan reverb:start > reverb.log 2>&1 &

            # optional: cache clear + optimize
            php artisan optimize:clear
            php artisan optimize